# This file was generated by GoReleaser. DO NOT EDIT.
cask "retna" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "a5152401217bfb8e6f57ad12bda97750a20ba6ad387d74f3cc219674f4602f83"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "075b29e4855f5881a8a58435271e3ce3e87f0e76a02d327e641241a88bcd2034"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbaed0c845c04ba6d2e056436f17340d16133e60b8c1af02a487f274d9d9c8a0"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b951a032fb1d2707baf633d22114bb464f3c72ae849a987bc14b02a6bd137b19"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_x86_64.tar.gz"
    end
  end

  name "retna"
  desc "Convert colors between color spaces and measure their contrast"
  homepage "https://github.com/d3uceY/Retna"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "retna"

  # No zap stanza required
end
