# This file was generated by GoReleaser. DO NOT EDIT.
cask "retna" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "1b5bd3decac8793de73b50a3ea5d7bb6e6efd9c653d6fdea5f2b77e599ede474"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "666ef04082ea971e253c598e43e25e7ff2eca9d0a39b47c5a752f098067dd98f"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3f7f54b96012487a71ae9d8a51941e836ccf3706d305f90d994ab302b144f4c"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "90c457d223cd00b0cf2da8745610533baa606ff81ae2fc708ae14c460ca44da9"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_x86_64.tar.gz"
    end
  end

  name "retna"
  desc "Convert colors between color spaces and measure their contrast"
  homepage "https://github.com/d3uceY/Retna"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "retna"

  # No zap stanza required
end
