# This file was generated by GoReleaser. DO NOT EDIT.
cask "retna" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "5fe61fcd134dae7d80d4e07d8fd750311ffeade6e9771aa82088caaed6a568ed"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "80b1f05aad6aec578690bda2e442340bcb1061a2b0e57feaec7b9997234a99f2"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8b3341ea789c8a0284d581bf1f00320ba7fe2a6e69959a5c7fdb169185f1c8a9"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0c83500b04f80aaf59bbd3abbb783924359f53c8c94dcc39f1163762379a29c"
      url "https://github.com/d3uceY/Retna/releases/download/v#{version}/retna_Linux_x86_64.tar.gz"
    end
  end

  name "retna"
  desc "Convert colors between color spaces and measure their contrast"
  homepage "https://github.com/d3uceY/Retna"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "retna"

  # No zap stanza required
end
